# Generated by Django 4.2.16 on 2025-11-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_subscriptionplan_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_advanced_analytics',
            field=models.BooleanField(default=False, help_text='Advanced Analytics feature'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='has_priority_support',
            field=models.BooleanField(default=False, help_text='24/7 Priority Support feature'),
        ),
    ]
