# Generated by Django 4.2.16 on 2025-11-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_subscriptionplan_has_advanced_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_free_trial',
            field=models.BooleanField(default=False, help_text='Free trial plan with booking restrictions'),
        ),
    ]
