# Generated by Django 4.2.16 on 2025-11-20 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_hotels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='hotels.hotel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('started', 'Started'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=20)),
                ('action_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='hotels.hotelsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hotels.hotelsubscription')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Twin', 'Twin'), ('Triple', 'Triple'), ('Quad', 'Quad')], default='Single', max_length=20)),
                ('category', models.CharField(choices=[('Standard', 'Standard'), ('Deluxe', 'Deluxe'), ('SuperDeluxe', 'Super Deluxe'), ('Executive', 'Executive'), ('Suite', 'Suite'), ('JuniorSuite', 'Junior Suite'), ('PresidentialSuite', 'Presidential Suite')], default='Standard', max_length=20)),
                ('bed', models.CharField(choices=[('King', 'King'), ('Queen', 'Queen'), ('DoubleBed', 'Double Bed'), ('TwinBed', 'Twin Bed')], default='DoubleBed', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved'), ('Dirty', 'Dirty'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'), ('Blocked', 'Blocked')], default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
            options={
                'unique_together': {('hotel', 'room_number')},
            },
        ),
    ]
