# Generated by Django 4.2.16 on 2025-11-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_category',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_status',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='size_sqft',
        ),
        migrations.RemoveField(
            model_name='room',
            name='special_features',
        ),
        migrations.RemoveField(
            model_name='room',
            name='view_type',
        ),
        migrations.AddField(
            model_name='hotel',
            name='icon',
            field=models.ImageField(blank=True, help_text='Hotel icon/logo', null=True, upload_to='hotel_icons/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_images/'),
        ),
    ]
