# Generated by Django 4.2.16 on 2025-11-24 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_remove_room_floor_remove_room_room_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('SEK', 'Swedish Krona (kr)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('MXN', 'Mexican Peso ($)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('NOK', 'Norwegian Krone (kr)'), ('INR', 'Indian Rupee (₹)'), ('PKR', 'Pakistani Rupee (₨)'), ('BRL', 'Brazilian Real (R$)'), ('RUB', 'Russian Ruble (₽)'), ('KRW', 'South Korean Won (₩)'), ('TRY', 'Turkish Lira (₺)'), ('ZAR', 'South African Rand (R)'), ('AED', 'UAE Dirham (د.إ)'), ('SAR', 'Saudi Riyal (﷼)'), ('EGP', 'Egyptian Pound (£)')], default='USD', max_length=3),
        ),
    ]
