# Generated by Django 4.2.16 on 2025-11-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='hotels.service'),
        ),
    ]
