# Generated by Django 4.2.16 on 2025-11-26 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_room_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
        migrations.AddField(
            model_name='room',
            name='additional_amenities',
            field=models.TextField(blank=True, help_text='Additional amenities (comma-separated)'),
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.CharField(choices=[('King', 'King Size Bed'), ('Queen', 'Queen Size Bed'), ('Double', 'Double Bed'), ('Twin', 'Twin Beds'), ('Single', 'Single Bed')], default='Double', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Room description'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=True, verbose_name='Air Conditioning'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False, verbose_name='Balcony'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_kitchenette',
            field=models.BooleanField(default=False, verbose_name='Kitchenette'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_living_room',
            field=models.BooleanField(default=False, verbose_name='Separate Living Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_minibar',
            field=models.BooleanField(default=False, verbose_name='Mini Bar'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_seating_area',
            field=models.BooleanField(default=False, verbose_name='Seating Area'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=True, verbose_name='TV'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True, verbose_name='Free Wi-Fi'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_work_desk',
            field=models.BooleanField(default=False, verbose_name='Work Desk'),
        ),
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='room_images/'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_guests',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of guests'),
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.PositiveIntegerField(default=250, help_text='Room size in square feet'),
        ),
        migrations.AddField(
            model_name='room',
            name='view_type',
            field=models.CharField(blank=True, choices=[('City', 'City View'), ('Garden', 'Garden View'), ('Ocean', 'Ocean View'), ('Mountain', 'Mountain View'), ('Pool', 'Pool View'), ('Courtyard', 'Courtyard View')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Standard', 'Standard Room'), ('Deluxe', 'Deluxe Room'), ('Superior', 'Superior Room'), ('Executive', 'Executive Suite'), ('Presidential', 'Presidential Suite')], default='Standard', max_length=20),
        ),
    ]
