# Generated by Django 4.2.16 on 2025-11-26 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_remove_room_bed_remove_room_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='hotels.roomcategory'),
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_categories', to='hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities'),
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='roomcategory',
            unique_together={('hotel', 'name')},
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_number', models.IntegerField(help_text='Floor number (e.g., 1, 2, 3, -1 for basement)')),
                ('floor_name', models.CharField(help_text='Floor name (e.g., Ground Floor, Mezzanine, Penthouse)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='hotels.hotel')),
            ],
            options={
                'ordering': ['floor_number'],
                'unique_together': {('hotel', 'floor_number')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.floor'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID or Registration Number', max_length=50)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Corporate discount percentage', max_digits=5)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, help_text='Credit limit for corporate bookings', max_digits=12)),
                ('payment_terms', models.CharField(blank=True, help_text='Payment terms (e.g., Net 30 days)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='hotels.hotel')),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'unique_together': {('hotel', 'name')},
            },
        ),
    ]
