# Generated by Django 4.2.16 on 2025-11-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_remove_room_type_room_amenities_room_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='category',
        ),
    ]
