# Generated by Django 4.2.16 on 2025-11-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_remove_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='google_drive_enabled',
            field=models.BooleanField(default=False, help_text='Enable Google Drive integration'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, help_text='Google Drive folder ID for storing documents', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_drive_share_email',
            field=models.EmailField(blank=True, help_text='Email to share uploaded documents with', max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_service_account_key',
            field=models.TextField(blank=True, help_text='Google Service Account JSON key'),
        ),
    ]
