# Generated by Django 4.2.16 on 2025-11-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_hotel_google_drive_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('V/C', 'Vacant (Clean)'), ('V/D', 'Vacant (Dirty)'), ('O/C', 'Occupied (Clean)'), ('O/D', 'Occupied (Dirty)'), ('Reserved', 'Reserved'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance'), ('Blocked', 'Blocked')], default='V/C', max_length=20),
        ),
    ]
