# Generated by Django 4.2.16 on 2025-11-28 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_increase_address_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
