# Generated by Django 4.2.16 on 2025-12-06 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_amenity_hotel_bedtype_hotel_floor_hotel_and_more'),
        ('hotels', '0016_alter_hotel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='approved_room_types',
            field=models.ManyToManyField(blank=True, help_text='Approved Room Types', to='configurations.roomtype'),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_mode',
            field=models.CharField(choices=[('company_pays', 'Company Pays'), ('guest_pays', 'Guest Pays')], default='company_pays', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('corporation', 'Corporation'), ('government', 'Government'), ('ngo', 'NGO/Non-Profit'), ('travel_agency', 'Travel Agency'), ('airline', 'Airline'), ('embassy', 'Embassy/Consulate'), ('multinational', 'Multinational Company'), ('local_business', 'Local Business'), ('other', 'Other')], default='corporation', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact Person Email', max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_end_date',
            field=models.DateField(blank=True, help_text='Contract End Date', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='Contract Start Date', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='corporate_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Corporate Discount (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='designation',
            field=models.CharField(blank=True, help_text='Designation', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company Logo (optional)', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile Number', max_length=25),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Registration/Tax Number (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='Website (optional)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, help_text='Registered Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Contact Person Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, help_text='Company Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=25),
        ),
        migrations.CreateModel(
            name='CompanyRoomRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate_per_night', models.DecimalField(decimal_places=2, help_text='Fixed rate per night', max_digits=12)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_rates', to='hotels.company')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.roomtype')),
            ],
            options={
                'verbose_name': 'Company Room Rate',
                'verbose_name_plural': 'Company Room Rates',
                'unique_together': {('company', 'room_type')},
            },
        ),
    ]
