# Generated by Django 4.2.16 on 2025-12-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_amenity_hotel_bedtype_hotel_floor_hotel_and_more'),
        ('hotels', '0017_company_approved_room_types_company_billing_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='approved_room_types',
            field=models.ManyToManyField(blank=True, help_text='Approved Room Types', related_name='approved_companies', to='configurations.roomtype'),
        ),
    ]
