# Generated by Django 4.2.16 on 2025-12-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_alter_company_approved_room_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='hotel',
        ),
        migrations.AddField(
            model_name='service',
            name='hotels',
            field=models.ManyToManyField(related_name='services', to='hotels.hotel'),
        ),
    ]
