# Generated by Django 4.2.16 on 2025-12-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_remove_service_hotel_service_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_type',
            field=models.CharField(choices=[('it_software', 'IT / Software'), ('banking_finance', 'Banking & Finance'), ('government_public', 'Government / Public Sector'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('manufacturing_industrial', 'Manufacturing & Industrial'), ('construction_realestate', 'Construction / Real Estate'), ('consulting_services', 'Consulting / Services'), ('logistics_transportation', 'Logistics & Transportation'), ('retail_fmcg', 'Retail / FMCG'), ('hospitality_tourism', 'Hospitality / Tourism'), ('ngo_nonprofit', 'NGO / Non-Profit'), ('other', 'Other')], default='it_software', max_length=30),
        ),
    ]
