# Generated by Django 4.2.16 on 2025-12-15 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0021_service_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'Status Changed'), ('assignment', 'Staff Assignment'), ('maintenance_request', 'Maintenance Request'), ('cleaning_completed', 'Cleaning Completed'), ('inspection', 'Room Inspection'), ('note_added', 'Note Added'), ('price_change', 'Price Updated'), ('amenity_change', 'Amenities Updated'), ('guest_checkin', 'Guest Check-in'), ('guest_checkout', 'Guest Check-out'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='hotels.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Activity Log',
                'verbose_name_plural': 'Room Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
