# Generated by Django 4.2.16 on 2025-12-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_roomactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomactivitylog',
            name='action',
            field=models.CharField(choices=[('status_change', 'Status Changed'), ('assignment', 'Staff Assignment'), ('maintenance_request', 'Maintenance Request'), ('cleaning_completed', 'Cleaning Completed'), ('inspection', 'Room Inspection'), ('note_added', 'Note Added'), ('price_change', 'Price Updated'), ('amenity_change', 'Amenities Updated'), ('guest_checkin', 'Guest Check-in'), ('guest_checkout', 'Guest Check-out'), ('payment_received', 'Payment Received'), ('reservation_created', 'Reservation Created'), ('reservation_cancelled', 'Reservation Cancelled'), ('housekeeping_assigned', 'Housekeeping Assigned'), ('other', 'Other')], max_length=50),
        ),
    ]
