# Generated by Django 4.2.17 on 2026-01-20 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0008_add_usage_to_bed_type'),
        ('hotels', '0023_alter_roomactivitylog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='configurations.roomcategory'),
        ),
    ]
