# Generated by Django 4.2.17 on 2026-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_add_room_category_to_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='has_ac',
            field=models.BooleanField(default=False, verbose_name='Air Conditioning'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_tv',
            field=models.BooleanField(default=False, verbose_name='TV'),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Free Wi-Fi'),
        ),
    ]
