# Generated by Django 4.2.16 on 2025-11-27 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_reservation_deleted_at_stay_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('expense_type', models.CharField(choices=[('food', 'Food & Beverage'), ('laundry', 'Laundry Service'), ('spa', 'Spa Services'), ('minibar', 'Minibar'), ('phone', 'Phone Charges'), ('internet', 'Internet'), ('parking', 'Parking'), ('transport', 'Transportation'), ('room_service', 'Room Service'), ('extra_bed', 'Extra Bed'), ('late_checkout', 'Late Checkout'), ('damage', 'Damage Charges'), ('other', 'Other Services')], default='other', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
