# Generated by Django 4.2.16 on 2025-11-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_assigned_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password',
            field=models.CharField(blank=True, help_text='Temporary storage for password to send in emails', max_length=128, null=True),
        ),
    ]
