# Generated by Django 4.2.16 on 2025-11-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Soft delete timestamp', null=True),
        ),
    ]
