# Generated by Django 4.2.16 on 2025-11-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_statement', models.TextField(help_text='Main mission statement')),
                ('problem_description', models.TextField(help_text='Description of the problem we solve')),
                ('solution_description', models.TextField(help_text='Description of our solution')),
                ('global_architecture_text', models.TextField(help_text='Global architecture description')),
                ('data_security_text', models.TextField(help_text='Data security description')),
                ('modern_tech_text', models.TextField(help_text='Modern technology description')),
                ('uptime_percentage', models.CharField(default='99.9%', max_length=10)),
                ('security_monitoring', models.CharField(default='24/7', max_length=20)),
                ('security_certification', models.CharField(default='ISO 27001', max_length=20)),
                ('compliance_standard', models.CharField(default='GDPR', max_length=20)),
                ('support_email', models.EmailField(default='support@aurastay.com', max_length=254)),
                ('support_phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('support_hours', models.CharField(default='24/7 Support', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
