# Generated by Django 4.2.16 on 2025-11-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='mission_icon',
            field=models.CharField(default='fas fa-target', help_text='FontAwesome icon class for mission section', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='problem_icon',
            field=models.CharField(default='fas fa-exclamation-triangle', help_text='FontAwesome icon class for problem section', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='solution_icon',
            field=models.CharField(default='fas fa-lightbulb', help_text='FontAwesome icon class for solution section', max_length=50),
        ),
    ]
