# Generated by Django 4.2.16 on 2025-11-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_aboutus_mission_icon_aboutus_problem_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='AuraStay', max_length=100)),
                ('company_description', models.TextField(default="The world's most advanced hotel management platform, designed for luxury hospitality.")),
                ('email', models.EmailField(default='info@aurastay.com', max_length=254)),
                ('phone', models.CharField(default='+1 (555) 123-4567', max_length=20)),
                ('address_line1', models.CharField(default='123 Business Ave', max_length=100)),
                ('address_line2', models.CharField(default='New York, NY 10001', max_length=100)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('copyright_text', models.CharField(default='© 2024 AuraStay Management Suite. All rights reserved.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer Content',
                'verbose_name_plural': 'Footer Content',
            },
        ),
    ]
