# Generated by Django 4.2.16 on 2025-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('super_admin_dashboard', 'Super Admin Dashboard'), ('owner_dashboard', 'Owner Dashboard'), ('employee_dashboard', 'Employee Dashboard'), ('profile', 'Profile Page'), ('landing', 'Landing Page'), ('about', 'About Page'), ('login', 'Login Page')], max_length=50, unique=True)),
                ('page_title', models.CharField(help_text='Main page title', max_length=200)),
                ('page_subtitle', models.TextField(help_text='Page subtitle/description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
            },
        ),
    ]
