# Generated by Django 4.2.16 on 2025-11-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='mission_description',
            field=models.TextField(blank=True, help_text='Description of our mission'),
        ),
    ]
