# Generated by Django 4.2.16 on 2025-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_aboutus_mission_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecontent',
            name='page_name',
            field=models.CharField(help_text="Unique identifier for the page (e.g., 'profile', 'subscription_plans_create')", max_length=50, unique=True),
        ),
    ]
