# Generated by Django 4.2.16 on 2025-11-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_pagecontent_page_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('work_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('hotel_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=100)),
                ('number_of_rooms', models.CharField(choices=[('1-50', '1-50 rooms'), ('51-150', '51-150 rooms'), ('151-300', '151-300 rooms'), ('300+', '300+ rooms')], max_length=20)),
                ('subject', models.CharField(choices=[('demo', 'Request a Demo'), ('general', 'General Inquiry'), ('support', 'Support'), ('pricing', 'Pricing Information'), ('partnership', 'Partnership Opportunity')], max_length=50)),
                ('message', models.TextField()),
                ('hear_about_us', models.CharField(blank=True, choices=[('google', 'Google Search'), ('social_media', 'Social Media'), ('referral', 'Referral'), ('advertisement', 'Advertisement'), ('conference', 'Conference/Event'), ('other', 'Other')], max_length=50)),
                ('privacy_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
