# Generated by Django 4.2.16 on 2025-11-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fas fa-calendar-check', 'Calendar Check'), ('fas fa-users', 'Users'), ('fas fa-chart-line', 'Chart Line'), ('fas fa-broom', 'Broom'), ('fas fa-credit-card', 'Credit Card'), ('fas fa-mobile-alt', 'Mobile'), ('fas fa-shield-alt', 'Shield'), ('fas fa-cog', 'Settings'), ('fas fa-bell', 'Bell'), ('fas fa-database', 'Database')], default='fas fa-cog', max_length=50)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('yellow', 'Yellow'), ('indigo', 'Indigo'), ('pink', 'Pink'), ('gray', 'Gray')], default='blue', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
