# Generated by Django 4.2.16 on 2025-11-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='copyright_text',
        ),
        migrations.AddField(
            model_name='footer',
            name='copyright_line1',
            field=models.CharField(default='© 2025 AuraStay. All rights reserved.', max_length=200),
        ),
        migrations.AddField(
            model_name='footer',
            name='copyright_line2',
            field=models.CharField(default='Design: MA Qureshi | Development: Momin Ali', max_length=200),
        ),
    ]
