# Generated by Django 4.2.16 on 2025-11-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_footer_copyright_text_footer_copyright_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Upload company logo (recommended: 200x200px)', null=True, upload_to='logos/'),
        ),
    ]
