# Generated by Django 4.2.16 on 2025-11-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_footer_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='purpose_icon',
            field=models.CharField(default='fas fa-rocket', help_text='FontAwesome icon class for purpose section', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='purpose_title',
            field=models.CharField(default='Our Purpose: Why AuraStay Exists', help_text='Title for the purpose section', max_length=200),
        ),
    ]
