# Generated by Django 4.2.16 on 2025-11-25 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_aboutus_purpose_icon_aboutus_purpose_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='trust_icon',
            field=models.CharField(default='fas fa-shield-alt', help_text='FontAwesome icon class for trust section', max_length=50),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='trust_subtitle',
            field=models.CharField(default='Built for the modern hospitality industry', help_text='Subtitle for the trust section', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='trust_title',
            field=models.CharField(default='Trust & Reliability', help_text='Title for the trust section', max_length=200),
        ),
    ]
