# Generated by Django 4.2.16 on 2025-11-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_aboutus_trust_icon_aboutus_trust_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='AuraStay', max_length=100)),
                ('company_logo', models.ImageField(blank=True, help_text='Main company logo used throughout the site (navbar, footer, login, etc.)', null=True, upload_to='site_logos/')),
                ('site_title', models.CharField(default='AuraStay - Hotel Management System', max_length=200)),
                ('site_description', models.TextField(default="The world's most advanced hotel management platform")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
