# Generated by Django 4.2.16 on 2025-11-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_siteconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Privacy Policy', max_length=200)),
                ('content', models.TextField(help_text='Privacy Policy content (supports HTML)')),
                ('effective_date', models.DateField(help_text='Date when this policy becomes effective')),
                ('version', models.CharField(default='1.0', help_text='Version number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TermsOfService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Terms of Service', max_length=200)),
                ('content', models.TextField(help_text='Terms of Service content (supports HTML)')),
                ('effective_date', models.DateField(help_text='Date when these terms become effective')),
                ('version', models.CharField(default='1.0', help_text='Version number', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms of Service',
                'verbose_name_plural': 'Terms of Service',
                'ordering': ['-created_at'],
            },
        ),
    ]
