# Generated by Django 4.2.16 on 2025-11-26 06:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_privacypolicy_termsofservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Privacy Policy content with rich text formatting'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Terms of Service content with rich text formatting'),
        ),
    ]
