# Generated by Django 4.2.16 on 2025-11-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_privacypolicy_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_configurations',
            field=models.BooleanField(default=False, help_text='Can create new configurations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_configurations',
            field=models.BooleanField(default=False, help_text='Can edit existing configurations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_configurations',
            field=models.BooleanField(default=False, help_text='Can delete configurations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_configurations',
            field=models.BooleanField(default=False, help_text='Can view configuration lists'),
        ),
    ]
