# Generated by Django 4.2.16 on 2025-11-27 22:23

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_can_add_configurations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_billing',
            field=models.BooleanField(default=False, help_text='Can create invoices'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_checkins',
            field=models.BooleanField(default=False, help_text='Can process check-ins'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_guests',
            field=models.BooleanField(default=False, help_text='Can add new guests'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_housekeeping',
            field=models.BooleanField(default=False, help_text='Can create housekeeping tasks'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_inventory',
            field=models.BooleanField(default=False, help_text='Can add inventory items'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_maintenance',
            field=models.BooleanField(default=False, help_text='Can report new issues'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_payments',
            field=models.BooleanField(default=False, help_text='Can process payments'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_pos',
            field=models.BooleanField(default=False, help_text='Can create orders'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_reservations',
            field=models.BooleanField(default=False, help_text='Can create reservations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_rooms',
            field=models.BooleanField(default=False, help_text='Can add new rooms'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_add_staff',
            field=models.BooleanField(default=False, help_text='Can add new staff'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_billing',
            field=models.BooleanField(default=False, help_text='Can edit billing'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_checkins',
            field=models.BooleanField(default=False, help_text='Can modify check-ins'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_guests',
            field=models.BooleanField(default=False, help_text='Can edit guest information'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_hotels',
            field=models.BooleanField(default=False, help_text='Can edit hotel settings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_housekeeping',
            field=models.BooleanField(default=False, help_text='Can update task status'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_inventory',
            field=models.BooleanField(default=False, help_text='Can update inventory'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_maintenance',
            field=models.BooleanField(default=False, help_text='Can update issue status'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_pos',
            field=models.BooleanField(default=False, help_text='Can modify orders'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_reservations',
            field=models.BooleanField(default=False, help_text='Can edit reservations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_rooms',
            field=models.BooleanField(default=False, help_text='Can edit room details'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_staff',
            field=models.BooleanField(default=False, help_text='Can edit staff details'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_guests',
            field=models.BooleanField(default=False, help_text='Can delete guest profiles'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_housekeeping',
            field=models.BooleanField(default=False, help_text='Can delete tasks'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_inventory',
            field=models.BooleanField(default=False, help_text='Can remove items'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_maintenance',
            field=models.BooleanField(default=False, help_text='Can close issues'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_pos',
            field=models.BooleanField(default=False, help_text='Can cancel orders'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_reservations',
            field=models.BooleanField(default=False, help_text='Can cancel reservations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_rooms',
            field=models.BooleanField(default=False, help_text='Can delete rooms'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_staff',
            field=models.BooleanField(default=False, help_text='Can remove staff'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_billing',
            field=models.BooleanField(default=False, help_text='Can view billing information'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_checkins',
            field=models.BooleanField(default=False, help_text='Can view check-ins'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_guests',
            field=models.BooleanField(default=False, help_text='Can view guest profiles'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_hotels',
            field=models.BooleanField(default=False, help_text='Can view hotel information'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_housekeeping',
            field=models.BooleanField(default=False, help_text='Can view housekeeping tasks'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_inventory',
            field=models.BooleanField(default=False, help_text='Can view inventory'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_maintenance',
            field=models.BooleanField(default=False, help_text='Can view maintenance issues'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_payments',
            field=models.BooleanField(default=False, help_text='Can view payments'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_pos',
            field=models.BooleanField(default=False, help_text='Can view POS orders'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can view financial reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reservations',
            field=models.BooleanField(default=False, help_text='Can view reservations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_rooms',
            field=models.BooleanField(default=False, help_text='Can view rooms'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_staff',
            field=models.BooleanField(default=False, help_text='Can view staff list'),
        ),
        migrations.AlterField(
            model_name='privacypolicy',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Privacy Policy content with rich text formatting', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='termsofservice',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Terms of Service content with rich text formatting', verbose_name='Content'),
        ),
    ]
