# Generated by Django 4.2.16 on 2025-11-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_can_add_billing_user_can_add_checkins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_add_companies',
            field=models.BooleanField(default=False, help_text='Can create company contracts'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_change_companies',
            field=models.BooleanField(default=False, help_text='Can edit company contracts'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_companies',
            field=models.BooleanField(default=False, help_text='Can delete company contracts'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_companies',
            field=models.BooleanField(default=False, help_text='Can view company contracts'),
        ),
    ]
