# Generated by Django 4.2.16 on 2025-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_can_add_companies_user_can_change_companies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Manager', 'Manager'), ('Receptionist', 'Receptionist/Front Desk'), ('Housekeeping', 'Housekeeping Staff'), ('Maintenance', 'Maintenance Staff'), ('Accountant', 'Accountant'), ('Staff', 'General Staff')], default='Staff', max_length=20),
        ),
    ]
