# Generated by Django 4.2.16 on 2025-12-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_new_role_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Trusted By Leading Hotels', max_length=100)),
                ('section_subtitle', models.CharField(default='Join thousands of hotels worldwide using AuraStay', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Content',
                'verbose_name_plural': 'Landing Page Content',
            },
        ),
        migrations.CreateModel(
            name='TrustedHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hotel name to display', max_length=100)),
                ('icon', models.CharField(default='fas fa-hotel', help_text='FontAwesome icon class (e.g., fas fa-hotel)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Show on landing page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trusted Hotel',
                'verbose_name_plural': 'Trusted Hotels',
                'ordering': ['order', 'name'],
            },
        ),
    ]
