# Generated by Django 4.2 on 2025-12-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_landingpagecontent_trustedhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_request_maintenance',
            field=models.BooleanField(default=False, help_text='Can create maintenance requests'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_update_room_status',
            field=models.BooleanField(default=False, help_text='Can update room cleaning status'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_housekeeping_schedule',
            field=models.BooleanField(default=False, help_text='Can view housekeeping schedules'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_room_assignments',
            field=models.BooleanField(default=False, help_text='Can view room assignments'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_room_status',
            field=models.BooleanField(default=False, help_text='Can view room cleaning status'),
        ),
    ]
