# Generated by Django 4.2.16 on 2025-11-20 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('occupancy', 'Occupancy Report'), ('revenue', 'Revenue Report'), ('adr', 'Average Daily Rate'), ('revpar', 'Revenue Per Available Room'), ('housekeeping', 'Housekeeping Performance'), ('maintenance', 'Maintenance Report'), ('guest_satisfaction', 'Guest Satisfaction'), ('financial', 'Financial Summary'), ('custom', 'Custom Report')], max_length=30)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('parameters', models.JSONField(default=dict)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('widgets', models.JSONField(default=list)),
                ('layout', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('occupancy_rate', 'Occupancy Rate'), ('adr', 'Average Daily Rate'), ('revpar', 'Revenue Per Available Room'), ('total_revenue', 'Total Revenue'), ('guest_satisfaction', 'Guest Satisfaction'), ('housekeeping_efficiency', 'Housekeeping Efficiency'), ('maintenance_response_time', 'Maintenance Response Time')], max_length=30)),
                ('value', models.DecimalField(decimal_places=4, max_digits=15)),
                ('date', models.DateField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='hotels.hotel')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('property', 'metric_type', 'date')},
            },
        ),
    ]
