# Generated by Django 4.2 on 2025-12-14 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_service_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('housekeeping', '0003_housekeepingtask_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousekeepingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift', models.CharField(choices=[('morning', 'Morning (6AM - 2PM)'), ('afternoon', 'Afternoon (2PM - 10PM)'), ('night', 'Night (10PM - 6AM)')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(blank=True, related_name='scheduled_cleanings', to='hotels.room')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housekeeping_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'shift'],
                'unique_together': {('staff', 'date', 'shift')},
            },
        ),
    ]
