# Generated by Django 4.2.16 on 2025-11-27 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_remove_room_category'),
        ('crm', '0002_guestprofile_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='hotels.company'),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='guest_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company')], default='individual', max_length=20),
        ),
    ]
