# Generated by Django 4.2.16 on 2025-11-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_guestprofile_company_guestprofile_guest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='national_id_card',
            field=models.CharField(blank=True, help_text='National Identity Card Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='guestprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
