# Generated by Django 4.2.16 on 2025-11-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_guestprofile_national_id_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='national_id_card',
            field=models.CharField(help_text='National Identity Card Number', max_length=50, unique=True),
        ),
    ]
