# Generated by Django 4.2.16 on 2025-11-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_guestprofile_national_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='national_id_card_image',
            field=models.ImageField(blank=True, help_text='National Identity Card Image', null=True, upload_to='national_id_cards/'),
        ),
    ]
