# Generated by Django 4.2.16 on 2025-11-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_guestprofile_national_id_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='google_drive_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID for ID card image', max_length=200),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='google_drive_file_link',
            field=models.URLField(blank=True, help_text='Google Drive file view link'),
        ),
    ]
