# Generated by Django 4.2.16 on 2025-11-28 00:37

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_guestprofile_google_drive_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofile',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
