# Generated by Django 4.2.16 on 2025-11-28 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_guestprofile_nationality'),
    ]

    operations = [
    ]
