# Generated by Django 4.2.16 on 2025-12-05 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20251128_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Safety', max_length=100),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Safety', max_length=20),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], help_text='Optional for record & reporting', max_length=20),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='passport_number',
            field=models.CharField(blank=True, help_text='For foreign guests', max_length=50),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='visa_number',
            field=models.CharField(blank=True, help_text='For international guest verification', max_length=50),
        ),
    ]
