# Generated by Django 4.2.16 on 2025-11-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
        ('staff', '0001_initial'),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceissue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_issues', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='maintenanceissue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='maintenanceissue',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_issues', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='maintenanceissue',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_issues', to='hotels.room'),
        ),
    ]
