# Generated by Django 4.2.16 on 2025-11-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceissue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
