# Generated by Django 4.2.16 on 2025-11-27 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_room_category_roomcategory_hotel_and_more'),
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_amenities', to='hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bedtype',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_bed_types', to='hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_floors', to='hotels.hotel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='config_room_types', to='hotels.hotel'),
            preserve_default=False,
        ),
    ]
