# Generated by Django 4.2 on 2025-12-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_alter_company_approved_room_types'),
        ('configurations', '0002_amenity_hotel_bedtype_hotel_floor_hotel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='hotel',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='hotels',
            field=models.ManyToManyField(related_name='config_room_types', to='hotels.hotel'),
        ),
    ]
