# Generated by Django 4.2.16 on 2025-12-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_alter_company_approved_room_types'),
        ('configurations', '0003_remove_roomtype_hotel_roomtype_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='bedtype',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='floor',
            name='hotel',
        ),
        migrations.AddField(
            model_name='amenity',
            name='hotels',
            field=models.ManyToManyField(related_name='config_amenities', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='bedtype',
            name='hotels',
            field=models.ManyToManyField(related_name='config_bed_types', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='floor',
            name='hotels',
            field=models.ManyToManyField(related_name='config_floors', to='hotels.hotel'),
        ),
    ]
