# Generated by Django 4.2.16 on 2025-12-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_remove_amenity_hotel_remove_bedtype_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bed_configuration',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='max_occupancy',
            field=models.IntegerField(default=2),
        ),
    ]
