# Generated by Django 4.2.17 on 2026-01-16 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_roomtype_bed_configuration_roomtype_max_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='bed_configuration',
        ),
    ]
