# Generated by Django 4.2.17 on 2026-01-16 04:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_alter_roomactivitylog_action'),
        ('configurations', '0006_remove_bed_configuration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='max_occupancy',
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_occupancy', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotels', models.ManyToManyField(related_name='config_room_categories', to='hotels.hotel')),
            ],
            options={
                'verbose_name_plural': 'Room Categories',
                'ordering': ['name'],
            },
        ),
    ]
