# Generated by Django 4.2.17 on 2026-01-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0007_remove_max_occupancy_add_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedtype',
            name='usage',
            field=models.CharField(blank=True, help_text='How this bed type is typically used (e.g., Single occupancy, Double occupancy, Kids bed)', max_length=100),
        ),
    ]
